### PR TITLE
Implement alternative number encodings

### PR DESCRIPTION
**Pull request by Fryuni**
As I proposed [on Reddit](https://www.reddit.com/r/rust/comments/12nw1pc/comment/jghhae3/?utm_source=share&utm_medium=web2x&context=3)

This includes two new encoding options
- `FullGammaEncoding`: uses the same algorithm as the default encoding but also applies it for integers.
- `BoundedGammaEncoding`: the optimization I proposed in my comment.

There is a todo in the code to flip the negative numbers so they follow the performance curve of the positive numbers, closer to zero uses fewer bits.
Currently, negative numbers will always use N + 1 bits.
This is part of the reason I made `i64` remain with the previous encoding for now.

Please tell me what you think.

### CODE REVIEW

**Comment by finnbear** [comment]
Hello!

Thanks for spending time thoroughly investigating a possible improvement to bitcode :heart:

We definitely want to add a way for users to invoke Elias Gamma encoding outside of lengths and enum variants. However, we're skeptical that a crate-wide setting is viable. At the very least, it isn't viable for the protocols in our use-case. _Some_ of our integers are randomly generated, meaning Elias Gamma encoding would be inefficient. Back when we used `bincode`, the crate-wide scope of number encoding was a severe annoyance for us.

Therefore, our current plan is to allow switching/hinting encodings at the type/field level. Three possible implementations immediately come to mind, two of which would even work within Serde. Ideally it would be a hint as opposed to a guarantee (we don't want to stabilize particular optimizations

P.S.: Don't worry about the failing test in the CI!

**Comment by Fryuni** [comment]
> However, we're skeptical that a crate-wide setting is viable. At the very least, it isn't viable for the protocols in our use-case. Some of our integers are randomly generated, meaning Elias Gamma encoding would be inefficient.

If those _some_ is less than half of the occurrences, you'd still benefit from the `BoundedGammaEncoding`. The numbers using less than half the bits would use Elias gamma, and those that use more would still use the normal representation with a single bit in front.

Besides, it is not really crate-wide as I've implemented. You can choose it per-root type. Even more, we can encode the encoding itself in the message so that some messages might use the more aggressive Elias gamma and not others.

> Therefore, our current plan is to allow switching/hinting encodings at the type/field level. Three possible implementations immediately come to mind, two of which would even work within Serde. Ideally it would be a hint as opposed to a guarantee (we don't want to stabilize particular optimizations).

I haven't worked a lot with Serde from the data-format implementation side, so I don't know how this would be done. If you could give me some hints (pun intended), I might look into it for this PR, it was really fun to do.

---

I'll work on optimizing negative numbers first.

**Comment by Fryuni** [comment]
> I think you're technically correct from a size perspective, but note that anything other than directly copying the integer bits is going to incur a performance penalty on all integers in addition to a size penalty on worst-case integers. It would really help to be selective about which integers are treated as gamma, delta, etc.

Indeed, I'm talking just about smaller size, not faster {en,de}coding. In fact, it is about 20% slower on my machine.

> We haven't decided which approach is best and we don't want to send anyone down a rabbit hole of implementation for something we ultimately decide against.

Don't worry. I'm doing this for the learning experience and the challenge of compact encoding. It's been years since I truly worked on bitwise optimizations, so this has been the highlight of my weekend (and it was raining rivers so I could not go out and touch grass).

Although I see that you guys are targeting more of a balance between compact encoding and speed, not just the most compact notation for a single scenario. On that note, and specially considering what you said "anything other than directly copying the integer bits is going to incur a performance penalty", I think an optimization on the direction of speed would be to flag numbers that are uniformly random to be byte aligned in the encoding, which would be even faster to decode at the expense of up to 7 bits.

> The approaches I was thinking of were:
> 
> * `struct BitcodeHint<T, const HINT: &str>(T)` e.g. `BincodeHint<u16, "gamma,delta">(7777)`. Major downside is that const generic strings are not yet stable.
> * `struct UserNewType(#[bitcode(gamma, delta)] u16)`. Major downside is that it isn't compatible with serde.
> * `struct UserNewType(#[serde(with = "bitcode::small_int")] u16)`. Major downside is that we must guarantee the existence of the named module so we wouldn't be comfortable exporting specific encodings like gamma or delta.

I would like the last one the best if it could be a function that returns a tuple of `(SerializerFn, DeserializerFn)`, but sadly it can´t.

> Just to re-iterate, we haven't decided if any of these are actually viable (and we may think of a better idea), so please don't spend time PR'ing any of them. If you have an opinion/idea, we're happy to hear it though.

What about doing something similar as [`serde_with`](https://docs.rs/serde_with/latest/serde_with/)? They added a macro on top of Serde's derive macros like so:

```rust
#[serde_as]
#[derive(Deserialize, Serialize)]
struct Foo {
    // Serialize with Display, deserialize with FromStr
    #[serde_as(as = "DisplayFromStr")]
    bar: u8,
}
```

We could have this:

```rust
#[bitcode::optimization] // Name TBD
#[derive(Deserialize, Serialize)]
struct Foo {
    // Optimize for that range with the most likely value becoming the most compact
    #[bitcode(likely_rage=50..=100, most_likely_value=60)]
    bar: u8,
}
```


> And, finally, here's an awful hack that probably works right now: `impl {Des, S}erialize` for your number new-type to serialize it as a `Vec<()>` with length equal to the number's value. Lengths are currently optimized with gamma and the `()`'s wont take any space at all.

This is horribly amazing in ways I can't explain. I hate that I love it.

**Comment by caibear** [comment]
We are working on derive macros that will allow something like this:
```rust
#[derive(Encode, Decode)]
struct Foo {
    a: u8,
    #[bitcode_hint(bounded_gamma)]
    b: i32,
    #[bitcode_hint(gamma)]
    #[bitcode(with_serde)]
    c: glam::IVec2, // might apply gamma to x and y
}

#[derive(Encode, Decode)]
enum Bar {
    #[bitcode_hint(weight = 100)]
    A, // might serialize as 1
    #[bitcode_hint(weight = 10)]
    B(u8), // might serialize as 00
    // Default weight is 1.
    C(String), // might serialize as 01
}
```
`#[bitcode(with_serde)]` will call `Serialize` or `Deserialize`.

Any `#[bitcode_hint(..)]` may result in changes to the output.

**Comment by finnbear** [comment]
With version `0.3.0`, we add a set of derive macros for fine-grained customization including with respect to numerical encoding. It would be, for example, possible to implement bounded gamma with a hint like `#[bitcode_hint(bounded_gamma)]`.

**Comment by caibear** [comment]
Specifically to add a new integer encoding you have to implement [Encoding](https://github.com/SoftbearStudios/bitcode/blob/e524f516ea881caf9660b390b686d62be20ca181/src/encoding/mod.rs#L22-L28). If you override [zigzag](https://github.com/SoftbearStudios/bitcode/blob/e524f516ea881caf9660b390b686d62be20ca181/src/encoding/mod.rs#L18-L20) to true it will make small negative numbers into small positive numbers. Then to allow `#[bitcode_hint(your_encoding)]` add it to [here](https://github.com/SoftbearStudios/bitcode/blob/e524f516ea881caf9660b390b686d62be20ca181/bitcode_derive/src/attribute.rs#L109) and [here](https://github.com/SoftbearStudios/bitcode/blob/e524f516ea881caf9660b390b686d62be20ca181/bitcode_derive/src/attribute.rs#L26) in the derive macro.

**Comment by finnbear** [comment]
Closing as stale and superseded by `#[bitcode_hint(gamma)]`; see past comments!

**Pull request closed without merging**
